module.exports = {
   disableEmoji: false,
   list: [
      'test',
      'feat',
      'fix',
      'chore',
      'docs',
      'refactor',
      'style',
      'ci',
      'perf',
      'data',
      'util',
      'layout',
      'font',
      'comp',
      'img',
      'middleware',
      'config',
      'model',
      'dto',
      'input',
      'file',
      'interface',
      'view',
      'lang',
      'typed',
      'secure',
      'guard',
      'controller',
      'decorator',
      'resolver',
      'service',
      'module',
   ],
   maxMessageLength: 250,
   minMessageLength: 3,
   questions: [
      'type',
      'scope',
      'subject',
      'body',
      'breaking',
      'issues',
      'lerna',
   ],
   scopes: [],
   types: {
      chore: {
         description: 'Build process or auxiliary tool changes',
         emoji: '🤖',
         value: 'chore',
      },
      ci: {
         description: 'CI related changes',
         emoji: '🎡',
         value: 'ci',
      },
      docs: {
         description: 'Documentation only changes',
         emoji: '✏️',
         value: 'docs',
      },
      feat: {
         description: 'A new feature',
         emoji: '🎸',
         value: 'feat',
      },
      fix: {
         description: 'A bug fix',
         emoji: '🐛',
         value: 'fix',
      },
      perf: {
         description: 'A code change that improves performance',
         emoji: '⚡️',
         value: 'perf',
      },
      refactor: {
         description:
            'A code change that neither fixes a bug or adds a feature',
         emoji: '💡',
         value: 'refactor',
      },
      release: {
         description: 'Create a release commit',
         emoji: '🏹',
         value: 'release',
      },
      style: {
         description: 'Markup, white-space, formatting, missing semi-colons...',
         emoji: '💄',
         value: 'style',
      },
      test: {
         description: 'Adding missing tests',
         emoji: '💍',
         value: 'test',
      },
      img: {
         description: 'Adding image',
         emoji: '🏞️',
         value: 'img',
      },
      module: {
         description: 'Adding module',
         emoji: '📰',
         value: 'module',
      },
      resolver: {
         description: 'Adding resolver',
         emoji: '📄',
         value: 'resolver',
      },
      comp: {
         description: 'Adding component',
         emoji: '🍚',
         value: 'comp',
      },
      font: {
         description: 'Adding font',
         emoji: '🆎',
         value: 'font',
      },
      layout: {
         description: 'Adding layout',
         emoji: '🎴',
         value: 'layout',
      },
      util: {
         description: 'Adding util',
         emoji: '🚙',
         value: 'util',
      },
      data: {
         description: 'Adding data',
         emoji: '🗂️',
         value: 'data',
      },
      controller: {
         description: 'Adding controller',
         emoji: '👓',
         value: 'controller',
      },
      middleware: {
         description: 'Adding Middleware',
         emoji: '🔒',
         value: 'middleware',
      },
      guard: {
         description: 'Adding guard',
         emoji: '🔐',
         value: 'guard',
      },
      service: {
         description: 'Adding Provider',
         emoji: '🚿',
         value: 'service',
      },
      config: {
         description: 'Adding Configuration',
         emoji: '⚙️',
         value: 'config',
      },
      model: {
         description: 'Adding model',
         emoji: '🗺️',
         value: 'model',
      },
      dto: {
         description: 'Adding dto',
         emoji: '💌',
         value: 'dto',
      },
      input: {
         description: 'Adding custom',
         emoji: '➕',
         value: 'input',
      },
      file: {
         description: 'Adding File',
         emoji: '🗄️',
         value: 'file',
      },
      interface: {
         description: 'Adding interface',
         emoji: '📌',
         value: 'interface',
      },
      view: {
         description: 'Adding view',
         emoji: '👀',
         value: 'view',
      },
      lang: {
         description: 'Adding Language',
         emoji: '🚩',
         value: 'lang',
      },
      typed: {
         description: 'Adding Typed',
         emoji: '🏀',
         value: 'typed',
      },
      secure: {
         description: 'Adding secure',
         emoji: '🔑',
         value: 'secure',
      },
      decorator: {
         description: 'Adding decorator',
         emoji: '📢',
         value: 'decorator',
      },
   },
};
