/**
 * Injection tokens
 */
export const PAGINATE_SERVICE_TOKEN = Symbol('PAGINATE_SERVICE');
export const PAGINATE_TOKEN = 'PAGINATION_TOKEN';
export const PAGINATE_LOADER = 'PAGINATION_LOADER';
export const PAGINATE_OPTIONS = 'PAGINATION_OPTIONS';
