/**
 * Injection tokens
 */
export const PAGINATION_SERVICE_TOKEN = Symbol('PAGINATE_SERVICE');
export const PAGINATION_TOKEN = 'PAGINATION_TOKEN';
export const PAGINATION_LOADER = 'PAGINATION_LOADER';
export const PAGINATION_OPTIONS = 'PAGINATION_OPTIONS';
